<!DOCTYPE html>
<html>
	<head>
		<title>Urban Chatter - The city's chaos. Organized.</title>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="/css/bootstrap.min.css" />
		<link rel="stylesheet" href="/css/styles.css" />
	</head>
	<body>
		<div class="container-fluid">
			<header>
			</header>
			<div class="jumbotron">
				<img src="images/uc-banner-1920.jpg" class="img-responsive" />
			</div>
			<div class="content" id="home">
                <div class="col-sm-4" id="featured">
                    <h2>Featured Posts</h2>
                    <div class="tiles"></div>
				</div>
				<div class="col-sm-4" id="recent">
					<h2>Recent Posts</h2>
					<div class="tiles"></div>
				</div>
				<div class="col-sm-4" id="new">
					<h2>New Posts</h2>
					<div class="tiles"></div>
				</div>
				<div class="clearfix"></div>
			</div>
			<!-- div id="about_us" class="row">
				<h2>About Us</h2>
				<div class="owner col-sm-4">
					<img src="images/uc-aadi-400.jpg" width="100%" class="author_profile" />
					<div class="author_desc">
						<h4>Aadithya Aigal</h4>
						<div class="author_text">Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. </div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="owner col-sm-4">
					<img src="images/uc-amit-400.jpg" width="100%" class="author_profile" />
					<div class="author_desc">
						<h4>Amit Nandan Periyapatna</h4>
						<div class="author_text">Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. </div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="owner col-sm-4">
					<img src="images/uc-sidda-400.jpg" width="100%" class="author_profile" />
					<div class="author_desc">
						<h4>Siddhanth Shetty</h4>
						<div class="author_text">Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. Some crap about us. </div>
					</div>
					<div class="clearfix"></div>
				</div>
			</div -->
			<div class="modal fade bs-example-modal-lg" id="login_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">Login</h4>
						</div>
						<div class="modal-body row">
							<div class="col-sm-5">
								<div class="form-group">
									<label for="username">Email Address</label>
									<input autocomplete="off" type="email" class="form-control" id="username" placeholder="Enter Username">
								</div>
								<div class="form-group">
									<label for="password">Password</label>
									<input type="password" autocomplete="off" class="form-control" id="password" placeholder="Enter Password">
								</div>
								<button id="login_submit" type="submit" class="btn btn-primary">Submit</button>
							</div>
							<div class="col-sm-5 col-sm-offset-2">
								<button id="facebook_login" type="button" class="btn btn-primary btn-lg">Sign in with Facebook</button>
							</div>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal fade bs-example-modal-lg" id="signup_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">Sign Up</h4>
						</div>
						<div class="modal-body row">
							<div class="col-sm-5">
								<div class="form-group">
									<label for="first_name">First Name</label>
									<input autocomplete="off" type="text" class="form-control" id="first_name" placeholder="Enter First Name">
								</div>
								<div class="form-group">
									<label for="last_name">Last Name</label>
									<input autocomplete="off" type="text" class="form-control" id="last_name" placeholder="Enter Last Name">
								</div>
								<div class="form-group">
									<label for="email">Email Address</label>
									<input autocomplete="off" type="email" class="form-control" id="email" placeholder="Enter Email Address">
								</div>
								<div class="form-group">
									<label for="email">Enter a Password</label>
									<input autocomplete="off" type="password" class="form-control" id="signup_password" placeholder="Enter a Password">
								</div>
								<div class="form-group">
									<label for="email">Re-enter Password</label>
									<input autocomplete="off" type="password" class="form-control" id="reenter_password" placeholder="Re-enter Password">
								</div>
								<button type="submit" id="signup_submit" class="btn btn-primary">Submit</button>
							</div>
							<div class="col-sm-5 col-sm-offset-2">
								<button id="facebook_signup" type="button" class="btn btn-primary btn-lg">Sign up via Facebook</button>
							</div>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript" src="/js/libs/jquery-1.11.0.min.js"></script>
		<script type="text/javascript" src="/js/libs/bootstrap.min.js"></script>
		<script type="text/javascript" src="/js/libs/jquery.visible.min.js"></script>
		<script type="text/javascript" src="/js/libs/tinymce.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function(){

				$.ajax({
					url : '/post/get-homepage',
					dataType : 'json',
					success : function(response){
						if(response.status == 1){
							createSection(response.featured, '#featured .tiles');
							createSection(response.recent, '#recent .tiles');
							createSection(response.new, '#new .tiles');
						}else{
							alert('There was a problem with the request. Please reload the page.')
						}
					},	
					error : function(response){
						alert('Error Occured');
					}
				})

				$(window).scroll(function(){
					if($('.jumbotron').visible(true)){
						$('.logo_row').css({
							'background-image' : 'none'
						})

					}else{
						$('.logo_row').css({
							'background-image' : 'url("/images/uc-logo-bg-1920-2.jpg")',
							'background-position' : 'center center',
							'background-repeat' : 'no-repeat'
						})
					}	
				})
			})
		</script>
	</body>
</html>