<?= $this->doctype() ?>
<!--[if lt IE 7 ]> <html class="ie ie6 no-js" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7 no-js" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8 no-js" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9 no-js" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--><html class="no-js" lang="en"><!--<![endif]-->
<!-- the "no-js" class is for Modernizr. -->
<head>
    <meta charset="utf-8">

   
    <title>Urban Chatter - The city's chaos. Organized.</title>
    <meta charset="UTF-8" />
    <link rel="shortcut icon" type="image/png" href="/images/uc_favico.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/bootstrap-tagsinput.css" />
    <link rel="stylesheet" href="/css/font-awesome.min.css" />
    <link rel="stylesheet" href="/css/styles.css" />
    <!-- Load Scripts with modernizr first -->
    <script src="/js/libs/modernizr-2.6.1.min.js"></script>
    <?php
        $this->headScript()->appendFile('/js/scripts.js?v=1');

        echo $this->jQuery();
        echo $this->headScript();
    ?>

</head>
<body>
    <header>

    </header>
    <div id="main">
        <?php echo $this->layout()->content; ?>
    </div>
    <footer>

    </footer>

</body>
</html>
