<?php 
	$response = $this->response;
	if($response['status'] == 0){
		echo "404 not Found";
		header("Location: /error");
	}
?>
	<body>
		<div id="blog_post" class="container-fluid">
			<header class="secondary">
			</header>
			<div class="blog_content">
			<?php 
				if($this->post_author_id == $this->userid){
			?>
				<div class="pull-right">
				 <a class="edit_blog_post" href='/edit-post/?id=<?php echo $this->post_id;?>'><button type="button" class="btn btn-success btn-xs">Edit</button></a>
				   <a class="delete_blog_post"><button type="button" class="btn btn-danger btn-xs">Delete</button></a>
				 </div>
			<?php 
				}
			?>
				 <div class="clearfix"></div>
				<h1 class='post_title'><?php echo $this->title;?></h1>
  				Author:&nbsp;<a class='username' href=''><?php echo $this->author;?></a>
  				<?php 
				 	if($this->loggedin == 1) {
				?>
  				<div class="likes_section">
					 <div class="likes pull-left">
					 <?php 
					 	if($this->liked == 1){
					 ?>
					   <a class="fa fa-thumbs-up liked"></a>
					 <?php 
					    }
					    else{
					 ?>  
					 	<a class="fa fa-thumbs-up like"></a>
					 <?php 
					 	}
					 	echo $this->likes;
					 ?>
					 
					 </div>
					 <div class="dislikes pull-left">
					 <?php 
					 	if($this->disliked == 1){
					 ?>
					         <a class="fa fa-thumbs-down disliked"></a>
					  <?php }
					  	else{
					  ?>
					  		 <a class="fa fa-thumbs-down dislike"></a>
					  <?php 
					  	}
					  	echo $this->dislikes;
					  ?>
					 </div>
					 <div class="clearfix"></div>
				</div>
				<?php 
					}
					else{
				?>
					<div class="likes_section">
					 <div class="likes pull-left">
					   <a class="fa fa-thumbs-up like" style="color: rgb(186, 186, 186);"></a> <?php echo $this->likes;?>
					 </div>
					 <div class="dislikes pull-left">
					         <a class="fa fa-thumbs-down dislike"></a> <?php echo $this->dislikes;?>
					 </div>
					 <div class="clearfix"></div>
				</div>
				<?php 
					}
				?>
  				<div class='blog_post'><?php echo $this->content;?></div>
  				<div class='tags'>
  					Tags:&nbsp;
  					<?php echo $this->tags;?>
  				</div>
  				<div class="comment_section">
  					<span class='comment_label'>Comments:</span>
  					<div class="comments_parent">
  					<?php 
  						$comments = $this->comments;
  						if($this->commentsPresent == 1){
  							foreach($comments as $a){
  					?>
			   		<div class="comment">
			   			<?php 
			   				if($this->userid == $a['comment_author_id']){
			   			?>
			   			
			   		   <a class="delete_comment pull-right" id="<?php echo $a["comment_id"]?>"><i class="fa fa-close"></i></a>
			   		   <?php } ?>
				       <div class="author"><a id='<?php echo $a['comment_author_id'];?>'><?php echo $a["comment_author"];?></a></div>
				       <div class="comment_text"><?php echo $a["content"];?></div>
			   		</div>
			   		<?php 
			   				}
			   			}
			   			else{
			   		?>
			   			<div class="comment">
			   				<a class="author"></a>
			   				<div class="comment_text">No Comments Present!</div>
			   			</div>
			   		<?php 
			   			}
			   		?>
			   		</div>
			   		<?php 
			   			if($this->loggedin == 1){
			   		?>
			   <div class="enter_comment">
			       <label>Enter Comment</label>
			       <textarea class="comment_post"></textarea>
			   </div>
			   <button class="btn btn-primary btn-xs pull-right comment_submit" type="button">Submit Comment</button>
			   <?php 
			   		}
			   ?>
			</div>
            </div>
            <div class="modal fade bs-example-modal-lg" id="login_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">Login</h4>
						</div>
						<div class="modal-body row">
							<div class="col-sm-5">
								<div class="form-group">
									<label for="username">Email Address</label>
									<input autocomplete="off" type="email" class="form-control" id="username" placeholder="Enter Username">
								</div>
								<div class="form-group">
									<label for="password">Password</label>
									<input type="password" autocomplete="off" class="form-control" id="password" placeholder="Enter Password">
								</div>
								<button id="login_submit" type="submit" class="btn btn-primary">Submit</button>
							</div>
							<div class="col-sm-5 col-sm-offset-2">
								<button id="facebook_login" type="button" class="btn btn-primary btn-lg">Sign in with Facebook</button>
							</div>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
			</div>
            <div class="modal fade bs-example-modal-lg" id="signup_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">Sign Up</h4>
						</div>
						<div class="modal-body row">
							<div class="col-sm-5">
								<div class="form-group">
									<label for="first_name">First Name</label>
									<input autocomplete="off" type="text" class="form-control" id="first_name" placeholder="Enter First Name">
								</div>
								<div class="form-group">
									<label for="last_name">Last Name</label>
									<input autocomplete="off" type="text" class="form-control" id="last_name" placeholder="Enter Last Name">
								</div>
								<div class="form-group">
									<label for="email">Email Address</label>
									<input autocomplete="off" type="email" class="form-control" id="email" placeholder="Enter Email Address">
								</div>
								<div class="form-group">
									<label for="email">Enter a Password</label>
									<input autocomplete="off" type="password" class="form-control" id="signup_password" placeholder="Enter a Password">
								</div>
								<div class="form-group">
									<label for="email">Re-enter Password</label>
									<input autocomplete="off" type="password" class="form-control" id="reenter_password" placeholder="Re-enter Password">
								</div>
								<button type="submit" id="signup_submit" class="btn btn-primary">Submit</button>
							</div>
							<div class="col-sm-5 col-sm-offset-2">
								<button id="facebook_signup" type="button" class="btn btn-primary btn-lg">Sign up via Facebook</button>
							</div>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
	<script type="text/javascript" src="/js/libs/jquery-1.11.0.min.js"></script>
	<script type="text/javascript" src="/js/libs/bootstrap.min.js"></script>
	<script type="text/javascript" src="/js/libs/jquery.visible.min.js"></script>
	<script type="text/javascript" src="/js/libs/tinymce.min.js"></script>
	<script type="text/javascript" src="/js/libs/bootstrap-tagsinput.min.js"></script>