	<body>
		<div id="blog_post" class="container-fluid">
			<header class="secondary">
			</header>
			<div class="blog_content">
				<h1 class='post_title'><?php echo $this->title;?></h1>
  				Author:&nbsp;<a class='username' href=''><?php echo $this->author;?></a>
  				<?php 
				 	if($this->loggedin == 1) {
				?>
  				<div class="likes_section">
					 <div class="likes pull-left">
					   <a class="fa fa-thumbs-up liked" style="color: rgb(186, 186, 186);"></a> <?php $this->select;?>
					 </div>
					 <div class="dislikes pull-left">
					         <a class="fa fa-thumbs-down dislike"></a> 200
					 </div>
					 <div class="clearfix"></div>
				</div>
				<?php 
					}
					else{
				?>
					<div class="likes_section">
					 <div class="likes pull-left">
					   <a class="fa fa-thumbs-up like" style="color: rgb(186, 186, 186);"></a> <?php $this->select;?>
					 </div>
					 <div class="dislikes pull-left">
					         <a class="fa fa-thumbs-down dislike"></a> 200
					 </div>
					 <div class="clearfix"></div>
				</div>
				<?php 
					}
				?>
  				<div class='blog_post'><?php echo $this->content;?></div>
  				<div class='tags'>
  					Tags:&nbsp;
  					<?php echo $this->tags;?>
  				</div>
            </div>
            <div class="modal fade bs-example-modal-lg" id="login_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">Login</h4>
						</div>
						<div class="modal-body row">
							<div class="col-sm-5">
								<div class="form-group">
									<label for="username">Email Address</label>
									<input autocomplete="off" type="email" class="form-control" id="username" placeholder="Enter Username">
								</div>
								<div class="form-group">
									<label for="password">Password</label>
									<input type="password" autocomplete="off" class="form-control" id="password" placeholder="Enter Password">
								</div>
								<button id="login_submit" type="submit" class="btn btn-primary">Submit</button>
							</div>
							<div class="col-sm-5 col-sm-offset-2">
								<button id="facebook_login" type="button" class="btn btn-primary btn-lg">Sign in with Facebook</button>
							</div>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
			</div>
            <div class="modal fade bs-example-modal-lg" id="signup_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">Sign Up</h4>
						</div>
						<div class="modal-body row">
							<div class="col-sm-5">
								<div class="form-group">
									<label for="first_name">First Name</label>
									<input autocomplete="off" type="text" class="form-control" id="first_name" placeholder="Enter First Name">
								</div>
								<div class="form-group">
									<label for="last_name">Last Name</label>
									<input autocomplete="off" type="text" class="form-control" id="last_name" placeholder="Enter Last Name">
								</div>
								<div class="form-group">
									<label for="email">Email Address</label>
									<input autocomplete="off" type="email" class="form-control" id="email" placeholder="Enter Email Address">
								</div>
								<div class="form-group">
									<label for="email">Enter a Password</label>
									<input autocomplete="off" type="password" class="form-control" id="signup_password" placeholder="Enter a Password">
								</div>
								<div class="form-group">
									<label for="email">Re-enter Password</label>
									<input autocomplete="off" type="password" class="form-control" id="reenter_password" placeholder="Re-enter Password">
								</div>
								<button type="submit" id="signup_submit" class="btn btn-primary">Submit</button>
							</div>
							<div class="col-sm-5 col-sm-offset-2">
								<button id="facebook_signup" type="button" class="btn btn-primary btn-lg">Sign up via Facebook</button>
							</div>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
	<script type="text/javascript" src="/js/libs/jquery-1.11.0.min.js"></script>
	<script type="text/javascript" src="/js/libs/bootstrap.min.js"></script>
	<script type="text/javascript" src="/js/libs/jquery.visible.min.js"></script>
	<script type="text/javascript" src="/js/libs/tinymce.min.js"></script>
	<script type="text/javascript" src="/js/libs/bootstrap-tagsinput.min.js"></script>