<!DOCTYPE html>
<html>
	<head>
		<title>Urban Chatter - The city's chaos. Organized.</title>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="/css/bootstrap.min.css" />
		<link rel="stylesheet" href="/css/bootstrap-tagsinput.css" />
		<link rel="stylesheet" href="/css/styles.css" />
	</head>
	<body>
		<div id="blog_post" class="container-fluid">
			<header class="secondary">
			</header>
			<div class="blog_content">
				<h1 class='post_title'><?php echo $this->title;?></h1>
  				Author:&nbsp;<a class='username' href=''><?php echo $this->username;?></a>
  				<div class='blog_post'><?php echo $this->content;?></div>
  				<div class='tags'>
  					Tags:&nbsp;
  					<?php echo $this->tags;?>
  				</div>
            </div>
		</div>
	</body>
	<script type="text/javascript" src="/js/libs/jquery-1.11.0.min.js"></script>
	<script type="text/javascript" src="/js/libs/bootstrap.min.js"></script>
	<script type="text/javascript" src="/js/libs/jquery.visible.min.js"></script>
	<script type="text/javascript" src="/js/libs/tinymce.min.js"></script>
	<script type="text/javascript" src="/js/libs/bootstrap-tagsinput.min.js"></script>
</html>